i = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(i)}')
print(f'Só tem espaços? {i.isspace()}')
print(f'É um númerico? {i.isnumeric()}')
print(f'É alfabético? {i.isalpha()}')
print(f'É alfanúmerico? {i.isalnum()}')
print(f'Está em maiúsculas? {i.isupper()}')
print(f'Está em minúsculas? {i.islower()}')
print(f'Está capitalizada? {i.title()}')
